/* This is the header for the accountselect class. It defines:
- what data the dialog receives after login
- what signal-slot methods the UI uses
- what internal state the class maintains
- what methods it overrides from Qt (paintEvent) */

#ifndef ACCOUNTSELECT_H
// Include guard: prevents multiple inclusion of this header
#define ACCOUNTSELECT_H

#include "account.h"
#include "avatar.h"
//#include "adminwindow.h"
#include <QDialog>
#include <QLabel>
#include <QMap>
#include <QPixmap>
#include <QPointer>
#include <QPushButton>
#include <QTimer>
#include <QNetworkAccessManager>

#include "apiclient.h"

// Forward declaration of the UI class generated by Qt Designer
namespace Ui {
class accountselect;
}

// accountselect is a dialog shown after login that allows the user to choose which account (debit or credit) to use
class accountselect : public QDialog
{
    Q_OBJECT
    
    public:
    // Constructor
    // - loginResult: data returned from a successful login
    // - api: shared API client used for backend communication
    // - inactivityTimer: global inactivity timer to prevent timeout during avatar selection
    // - parent: optional parent widget
    explicit accountselect(
        const LoginResultDto& loginResult,
        ApiClient* api,
        QTimer* inactivityTimer = nullptr,
        QWidget *parent = nullptr
    );
    // Destructor
    ~accountselect();
    
    protected:
    // Overridden paint event to allow custom background drawing
    void paintEvent(QPaintEvent *event) override;
    void resizeEvent(QResizeEvent *event) override;
    
    private slots:
    // Slot called when the Debit button is clicked
    void on_btnSelectDebit_clicked();
    // Slot called when the Credit button is clicked
    void on_btnSelectCredit_clicked();
    // Slot called when the Edit Avatar button is clicked
    void openAvatarDialog();

private:
    // Pointer to the UI elements generated from accountselect.ui
    Ui::accountselect *ui;
    
    // Shared API client (not owned by this dialog)
    ApiClient* m_api;
    // Login data containing user info and available accounts
    LoginResultDto m_login;
    
    // Global inactivity timer (not owned, just referenced)
    QTimer* m_inactivityTimer;
    
    // Avatar dialog shown before account selection
    QPointer<avatar> avatarDialog = nullptr;
    QLabel* m_avatarPreview = nullptr;
    QPushButton* m_btnEditAvatar = nullptr;
    QPixmap m_avatarPixmap;
    
    // Currently selected account type ("debit" or "credit")
    QString selectedAccountType;
    // Maps account type strings ("debit", "credit") to account IDs
    QMap<QString, int> accountIdByType;
    
    // Opens the main account window for the selected account
    void openAccountWindow();
    void openAdminWindow();
    void setAvatarPreview(const QPixmap& pixmap);
    void loadAvatarFromUrl(const QString& url);
    void layoutHeaderControls();
    
    QNetworkAccessManager* m_avatarNam = nullptr;
};

#endif // ACCOUNTSELECT_H
